### ISSUE TITLE
five_mem_node bench fails with panic

### ISSUE THREAD

**Issue by r8d8** [pingcap/raft-rs#212] opened 2019-04-10 06:31 UTC
**Describe the bug**
I am trying to run `five_mem_node` example using next command:

**To Reproduce**
1. Run five_mem_node example  
```shell
$ cargo run --color=always --package raft --example five_mem_node
```
2. See error

**Expected behavior**
Should run without failure

**System information**
* CPU architecture: x86
* Distribution and kernel version:  Ubuntu 18.04 LTS, kernel 4.15.0-47-generic
* SELinux on?: no
* Any other system details we should know?: Rust 1.35.0-nightly

**Comment by siddontang** [comment] 2019-04-10 09:14
PTAL @Hoverbear

**Comment by Hoverbear** [comment] 2019-04-10 19:43
Duplicate of https://github.com/pingcap/raft-rs/issues/205, fixed by https://github.com/pingcap/raft-rs/pull/213

**Comment by Hoverbear** [comment] 2019-04-10 19:43
Thanks for reporting this, it's already been reported. Please follow the linked issue.

**Closed** 2019-06-11 18:03 UTC
Labels: Duplicate
